#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.example.kechengsheji.model
  mapperLocations: classpath:mapper/**/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kechengsheji?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
# spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

